// these are where i put my filters 

Caman.Filter.register("blackAndWhite", function(grey) {

      this.greyscale();
      this.sepia(10);
      this.exposure(10);
      this.contrast(15);
      return this.vignette("60%",35);
  });

Caman.Filter.register("bright", function(grey) {

      this.brightness(7);
      this.exposure(5);
      this.contrast(16);
      return this.vibrance(7);
  });


// Generated by CoffeeScript 1.6.3
(function() {
  var presetBusy, presetCaman, render, renderPreset,
  presetCaman = null;

 
  presetBusy = false;

  renderPreset = function(preset) {
    var $filter, name;
    if (presetBusy) {
      return;
    }
    $("#PresetFilters a").removeClass('Active');
    $filter = $("#PresetFilters a[data-preset='" + preset + "']");
    name = $filter.html();
    $filter.addClass('Active').html('Rendering...');
    presetBusy = true;
    presetCaman.revert(false);
    presetCaman[preset]();
    return presetCaman.render(function() {
      $filter.html(name);
      return presetBusy = false;
    });
  };

  $(document).ready(function() {
    presetCaman = Caman('#preset-example');
    $('.FilterSetting input').each(function() {
      var filter;
      filter = $(this).data('filter');
      return filters[filter] = $(this).val();
    });
    $('#Filters').on('change', '.FilterSetting input', function() {
      var filter, value;
      filter = $(this).data('filter');
      value = $(this).val();
      filters[filter] = value;
      $(this).find('~ .FilterValue').html(value);
      return render();
    });
    return $('#PresetFilters').on('click', 'a', function() {
      return renderPreset($(this).data('preset'));
    });
  });

}).call(this);