/*------------------------------------------------------------------------------
          DROPDOWNS
------------------------------------------------------------------------------*/

  function DropDown(el) {
    this.dd = el;
    this.initEvents();
  }

  DropDown.prototype = {
    initEvents : function() {
      var obj = this;

      obj.dd.on('click', function(event){
        $(this).toggleClass('active');
        event.stopPropagation();
      }); 
    }
  };

  $(function() {

    var dd = new DropDown( $('.dd') );

    $(document).click(function() {
      // all dropdowns
      $(dd).removeClass('active');
    });

  });

/*------------------------------------------------------------------------------
         CAMAN
------------------------------------------------------------------------------*/

// these are where i put my filters 

Caman.Filter.register("blackAndWhite", function(grey) {

      this.greyscale();
      this.sepia(10);
      this.exposure(10);
      this.contrast(15);
      return this.vignette("60%",35);
  });

Caman.Filter.register("bright", function(grey) {

      this.brightness(7);
      this.exposure(5);
      this.contrast(16);
      return this.vibrance(7);
  });


// Generated by CoffeeScript 1.6.3
(function() {
  var presetBusy, presetCaman, render, renderPreset,
  presetCaman = null;

 
  presetBusy = false;

  renderPreset = function(preset) {
    var $filter, name;
    if (presetBusy) {
      return;
    }
    $("#PresetFilters a").removeClass('Active');
    $filter = $("#PresetFilters a[data-preset='" + preset + "']");
    name = $filter.html();
    $filter.addClass('Active').html('Rendering...');
    presetBusy = true;
    presetCaman.revert(false);
    presetCaman[preset]();
    return presetCaman.render(function() {
      $filter.html(name);
      return presetBusy = false;
    });
  };

  $(document).ready(function() {
    presetCaman = Caman('#preset-example');
    //close modal --- need to add saving out the canvas and adding to the other canvas
    $(" #done ").click(function(){ 
        //grab the context from your destination canvas
        var destCtx = document.getElementById('canvas2').getContext('2d');
        destCtx.drawImage(document.getElementById('preset-example'), 0, 0);    
        $("#imageEdit").hide();
    });
    return $('#PresetFilters').on('click', 'a', function() {
      return renderPreset($(this).data('preset'));
    });
  });

}).call(this);

/*------------------------------------------------------------------------------
         Save and Add to Canvas
------------------------------------------------------------------------------*/






